import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../components/Bar'
import Footer from '../components/Footer'
import Main from './main'
import { Grid } from '@mui/material'

export default function Home() {
  return (
    <Grid>
      <Head>
        <title>MeetMind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>
      <Grid item sx={{ maxWidth: {lg:'80%', xs:'calc(100% - 40px)',xl:'1440px'}, marginLeft:{xs:'20px', lg:'10%', xl:'auto'}, marginRight:{xs:'20px', lg:'10%',xl:'auto'}, 
      minHeight:'100vh', height: 'auto', position:'relative'}}>
      <ResponsiveAppBar />
        <Main />
      <Footer />
      </Grid>
    </Grid>
  )
}